#!/bin/bash

version=$(git rev-parse HEAD)

test -e cookbooks/version/attributes/default.rb && {
  sed -ie "s/%VERSION%/$version/" cookbooks/version/attributes/default.rb
  knife cookbook upload -o ./cookbooks version --force
  echo " => INFO: Set version: $version"
}


exit 0
