#!/usr/bin/env ruby

# This file was placed here by GitLab.
# IT IS DEPRECATED NOW.
# All GitLab logic handled by update hook

# Undev
require 'rubygems'
require 'tempfile'

current_dir = File.expand_path(Dir.pwd)

args = $stdin.read.split(/\s/)

Tempfile.open('git-hook-input') do |tempfile|
  $stdin.each_line { |line| tempfile.print(line) }
  tempfile.close

  Dir.chdir(current_dir) do
    system("echo #{args * ' '} | #{current_dir}/hooks/post-receive-action-origin")
  end

  Dir.chdir(current_dir) do
    system("cat #{tempfile.path} | #{current_dir}/hooks/post-receive-action-undev #{args * ' '}")
  end

  # preseed/preseed
  if current_dir == "/var/git/repositories/preseed/preseed.git"
    system("cat #{tempfile.path} | #{current_dir}/hooks/post-receive-pxe")
  end

  # coreplayer
  if current_dir == "/var/git/repositories/flash-player/coreplayer.git"
    system("echo #{args * ' '} | #{current_dir}/hooks/post-receive-coreplayer")
  end

  # megaadmins/chef
  if current_dir == "/var/git/repositories/megaadmins/chef.git"
    system("echo #{args * ' '} | #{current_dir}/hooks/post-receive-megaadmins-chef")
  end
end
