#!/usr/bin/env ruby

require 'dns/zonefile'

def get_serial(zone)
  zone = DNS::Zonefile.parse(zone)
  return zone.soa.serial.to_s
end

while data = gets
  oldrev, newrev, ref = data.chomp.split(" ")

  if oldrev == "0000000000000000000000000000000000000000"
    # initial commit
    exit 0 
  end

  old_zone = `git show #{oldrev}:db 2>/dev/null`
  new_zone = `git show #{newrev}:db 2>/dev/null`

  if old_zone == ""
    exit 0
  end

  if old_zone == new_zone
    # no changes in zone file
    exit 0
  end

  old_serial = get_serial(old_zone)
  new_serial = get_serial(new_zone)

  if old_serial >= new_serial
    puts "\e[1m\e[31m => ERROR: Wrong serial!\e[0m"
    exit 1
  end
end
