#!/usr/bin/env ruby

# -*- coding: utf-8 -*-
#--
#   Copyright (C) 2008 Johan Sørensen <johan@johansorensen.com>
#   Copyright (C) 2009 Marius Mårnes Mathiesen <marius.mathiesen@gmail.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

require 'rubygems'

current_dir = File.expand_path(Dir.pwd)
args = $stdin.read.split(/\s/)

Dir.chdir(current_dir) do
  system("echo #{args * ' '} | #{current_dir}/hooks/pre-receive-action-origin")

  # megaadmins/chef
  if current_dir == "/var/git/repositories/megaadmins/chef.git"
    system("echo #{args * ' '} | #{current_dir}/hooks/pre-receive-megaadmins-chef")
    exit_status = $?
    if not exit_status.success?
      puts "=> Failed upload"
      $stdout.flush
      exit!(1)
    end
  elsif File.basename(File.dirname(current_dir)) == "dns-zones"
    system("echo #{args * ' '} | #{current_dir}/hooks/pre-receive-dns-zones")
    exit_status = $?
    if not exit_status.success?
      puts "=> Failed upload"
      $stdout.flush
      exit!(1)
    end
  end
end
